using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Telesci.Anomaly;
using Content.Shared._ES.Telesci.Anomaly.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._ES.Telesci.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESAnomalyConsoleWindow : FancyWindow
{
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private string _currentSelected = string.Empty;

    public ESAnomalyConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnomalyList.OnItemSelected += OnAnomalySelected;
    }

    public void Update(ESAnomalyConsoleBuiState state)
    {
        AnomalyList.Clear();

        foreach (var data in state.Anomalies)
        {
            var (name, _, _) = data;

            AnomalyList.AddItem(name,
                metadata: new AnomalyData
            {
                Name = data.name,
                Signals = data.signals,
                Count = data.signalCount,
            });
        }
        AnomalyList.SortItemsByText();
        if (AnomalyList.FirstOrDefault(e => e.Text == _currentSelected) is { } item)
            item.Selected = true;
    }

    private void OnAnomalySelected(ItemList.ItemListSelectedEventArgs obj)
    {
        var metaData = AnomalyList[obj.ItemIndex].Metadata;
        if (metaData is not AnomalyData data)
            return;
        _currentSelected = data.Name;

        var name = data.Name;
        var signals = data.Signals;
        var count = data.Count;

        NameLabel.Text = Loc.GetString("es-anomaly-console-signal-name", ("name", name));

        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("es-anomaly-console-signal-header"));
        msg.PushNewline();
        for (var i = 0; i < count; i++)
        {
            if (signals.TryGetValue(i, out var signal))
            {
                var signalText = ESSharedAnomalySystem.GetSignalString(_loc, signal);
                if (i == signals.Count - 1)
                {
                    msg.AddMarkupOrThrow(Loc.GetString("es-anomaly-console-signal-current-fmt", ("freq", signalText)));
                }
                else
                {
                    msg.AddMarkupOrThrow(Loc.GetString("es-anomaly-console-signal-fmt", ("freq", signalText)));
                }
            }
            else
            {
                msg.AddMarkupOrThrow(Loc.GetString("es-anomaly-console-signal-locked"));
            }
            msg.PushNewline();
        }
        SequenceLabel.SetMessage(msg, tagsAllowed: null);
    }

    private struct AnomalyData
    {
        public string Name;
        public List<ESAnomalySignal> Signals;
        public int Count;
    }
}

